---
- name: Reboot
  gather_facts: false
  connection: ansible.netcommon.network_cli
  vars:
    ansible_user: vyos
    ansible_network_os: vyos.vyos.vyos

  hosts: router
  tasks:

    - name: Reboot
      ansible.netcommon.cli_command:
        command: "reboot now"
